### ISSUE TITLE
Feature: Add a toggle to hide multi disc games cover art

### ISSUE THREAD

**Issue by Mullmania** [mrneo240/openmenu#7]
When there are games with multiple discs, the cover art is repeated, in some cases showing 4 of the same cover (D2 is an example). Adding a toggle to hide all covers except for disc 1 in the Grid and standard menu would clean up the clutter.

**Comment by mrneo240** [comment]
How do you propose to launch the other discs?

**Comment by Mullmania** [comment]
You unhide them with the toggle (button or menu "on"/"off" option). Also,
doesn't the GDEMU go to the next disc by pushing the button on the PCB?

**Comment by Drakonas** [comment]
Yeah, to add my thoughts to this, I think having it merged or have the other discs hidden would be nice. Most games have most content on the first disc as the last one tends to have a lot of video files typically.

So the first disc would be used the most generally. Also, Mullmania is correct. The GDEmu can go to the next disc with the button on the PCB, and this is generally super quick, so ideally you could just load the game you want, then tap the button 1-3 times to get to the disc you want.

This saves scroll space, and I wish the GDMenu had done this, because otherwise the PCB button seems slightly more pointless except when you need to actually swap in-game.

**Comment by Toyota-ice** [comment]
The skip disc button is not working on all of the clone gdemus

**Comment by Drakonas** [comment]
> The skip disc button is not working on all of the clone gdemus

I didn't know that was an issue. But again, I repeat that it could be added as an option rather than permanent. Or use my proposed "Hide game" feature, if that's possible.

**Comment by Mullmania** [comment]
Yes my original request is that this be an on/off toggle so that it is not
mandatory.

**Comment by mrneo240** [comment]
I like the idea of compacting multi disc titles into a single file and giving the user choice which to launch

**Comment by Mullmania** [comment]
If that is possible that’s a great solution. Like a pop up asking which
disc to launch.

**Comment by Drakonas** [comment]
The downside of asking which disc to boot is the current GDEmu disc files do not actually indicate what disc number they are.

Either that data would have to be added to GDMenuCardManager's install functions, or the user would be expected to have all discs in order and named appropriately.

Naming could be handled two ways with the latter method.

1. Name them with GD1, GD2, etc at the end of the game name. This not ideal though since there's a character limit and some game names max out and won't fit "GD1" at the end.
2. Name all discs the same and have openmenu detect games with the same name and treat them as a multidisc setup. This would require the user to make sure that games do have different names for different games.

Personally I think the latter method is not asking too much of the users, and most installs will have the games set up this way already anyway. Plus this method brings less coding work, as I expect adding the code to have disc numbers installed to the SD card and then have openmenu detect these disc numbers would be a lot more work than keeping SDCardMenuManager stay the same, and have openmenu check for games with the same name.

Obviously one of the things to worry about is overhead on having openmenu look up that information at boot every time. One of the nicest things about openmenu is the menu's loading time is so sublime compared to GDMenu. It'd be nice to make sure it's a priority to be careful with adding too much to the load time.

**Comment by Mullmania** [comment]
Good points. Each games meta data has number of discs and which disc
number. I think this can be leveraged rather than a naming scheme. It’s
already built into the SD card manager and openmenu.

mrneo - correct me if I am wrong.

**Comment by mrneo240** [comment]
I believe this should solve your feature request:
![https://cdn.discordapp.com/attachments/623579895636951040/866505405286187048/nullDC_Win32_Release_21_07_18_22-21-56_QokHp.png](https://cdn.discordapp.com/attachments/623579895636951040/866505405286187048/nullDC_Win32_Release_21_07_18_22-21-56_QokHp.png)



Video here showing it off:
[https://streamable.com/j26aw5](https://streamable.com/j26aw5)

**Comment by Drakonas** [comment]
Thanks you good sir. I want aware the game had this data
